-- CreateTable
CREATE TABLE "prisma7_spike_users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "prisma7_spike_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "prisma7_spike_posts" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "title" TEXT NOT NULL,
    "author_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "prisma7_spike_posts_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "prisma7_spike_users_email_key" ON "prisma7_spike_users"("email");

-- CreateIndex
CREATE INDEX "prisma7_spike_posts_author_id_idx" ON "prisma7_spike_posts"("author_id");

-- AddForeignKey
ALTER TABLE "prisma7_spike_posts" ADD CONSTRAINT "prisma7_spike_posts_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "prisma7_spike_users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
